Mutation:
  type: object
  config:
    fields:
      create_author:
        type: Author!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\CreateAuthorMutation::createAuthor", [args])'
        args:
          input:
            type: AuthorInput!
      update_author:
        type: Author!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\UpdateAuthorMutation::updateAuthor", [args])'
        args:
          id:
            type: Int
          input:
            type: AuthorInput!
      create_post:
        type: Post!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\CreatePostMutation::createPost", [args])'
        args:
          input:
            type: PostInput!
