Post:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\PostResolver", [info, value, args])'
    fields:
      id:
        type: Int
      title:
        type: String
      body:
        type: String
      author:
        type: Author
